// fc_ioctl.h
//
// Define control codes for Fc_pcie driver
//

#ifndef __fc_ioctl__h_
#define __fc_ioctl__h_

#define FIDEUN	FILE_DEVICE_UNKNOWN
#define MEBU	METHOD_BUFFERED
#define FIANAC	FILE_ANY_ACCESS


#define IOCTL_READ_PCI_CONFIGURATION		CTL_CODE(FIDEUN, 0x720, MEBU, FIANAC)



#define IOCTL_XILRESET					CTL_CODE(FIDEUN, 0x800, MEBU, FIANAC)
#define IOCTL_XILLOAD					CTL_CODE(FIDEUN, 0x801, MEBU, FIANAC)
#define IOCTL_XILTEST					CTL_CODE(FIDEUN, 0x802, MEBU, FIANAC)
#define IOCTL_RESET_CORE				CTL_CODE(FIDEUN, 0x803, MEBU, FIANAC)
#define IOCTL_WRITE_APPLYBACKPRESSURE	CTL_CODE(FIDEUN, 0x804, MEBU, FIANAC)
#define IOCTL_READ_APPLYBACKPRESSURE	CTL_CODE(FIDEUN, 0x805, MEBU, FIANAC)

#define IOCTL_READ_STATUS			CTL_CODE(FIDEUN, 0x810, MEBU, FIANAC)
#define IOCTL_WRITE_STATUS			CTL_CODE(FIDEUN, 0x811, MEBU, FIANAC)
#define IOCTL_SET_ADR_MASTER		CTL_CODE(FIDEUN, 0x820, MEBU, FIANAC)
#define IOCTL_READ_ADR_MASTER		CTL_CODE(FIDEUN, 0x830, MEBU, FIANAC)
#define IOCTL_WRITE_PARAMETERS		CTL_CODE(FIDEUN, 0x840, MEBU, FIANAC)	
#define IOCTL_READ_PARAMETERS		CTL_CODE(FIDEUN, 0x841, MEBU, FIANAC)	
#define IOCTL_SET_RAM_TX_RX			CTL_CODE(FIDEUN, 0x850, MEBU, FIANAC)	
#define IOCTL_READ_RAM_TX_RX		CTL_CODE(FIDEUN, 0x851, MEBU, FIANAC)	
#define IOCTL_EN_DIS_TIMER			CTL_CODE(FIDEUN, 0x852, MEBU, FIANAC)	
#define IOCTL_READ_TIMER			CTL_CODE(FIDEUN, 0x853, MEBU, FIANAC)	
#define IOCTL_RESET_COUNT_FRAME_TX	CTL_CODE(FIDEUN, 0x854, MEBU, FIANAC)	
#define IOCTL_READ_COUNT_FRAME_TX	CTL_CODE(FIDEUN, 0x855, MEBU, FIANAC)	
#define IOCTL_RESET_COUNT_FRAME_RX	CTL_CODE(FIDEUN, 0x856, MEBU, FIANAC)	
#define IOCTL_READ_COUNT_FRAME_RX	CTL_CODE(FIDEUN, 0x857, MEBU, FIANAC)	
#define IOCTL_WRITE_ADR_FC_MANAGE	CTL_CODE(FIDEUN, 0x880, MEBU, FIANAC)	
#define IOCTL_WRITE_DATA_FC_MANAGE	CTL_CODE(FIDEUN, 0x890, MEBU, FIANAC)	
#define IOCTL_READ_DATA_FC_MANAGE	CTL_CODE(FIDEUN, 0x8A0, MEBU, FIANAC)	
#define IOCTL_START_FC_TX			CTL_CODE(FIDEUN, 0x8B0, MEBU, FIANAC)	
#define IOCTL_WRITE_IDLE_SEQ		CTL_CODE(FIDEUN, 0x8B1, MEBU, FIANAC)	
#define IOCTL_READ_IDLE_SEQ         CTL_CODE(FIDEUN, 0x8B2, MEBU, FIANAC)
#define IOCTL_READ_STATUS_RX		CTL_CODE(FIDEUN, 0x8C0, MEBU, FIANAC)
#define IOCTL_READ_STATISTICS		CTL_CODE(FIDEUN, 0x8E0, MEBU, FIANAC)	
#define IOCTL_READ_CONFIG_STATUS	CTL_CODE(FIDEUN, 0x8F0, MEBU, FIANAC)

//-новые для прошивки 134------
#define IOCTL_RESET_TX              CTL_CODE(FIDEUN, 0x8F1, MEBU, FIANAC)
#define IOCTL_RESET_RX              CTL_CODE(FIDEUN, 0x8F2, MEBU, FIANAC)
#define IOCTL_WRITE_TX_SLOT         CTL_CODE(FIDEUN, 0x8F3, MEBU, FIANAC)
#define IOCTL_WRITE_RX_SLOT         CTL_CODE(FIDEUN, 0x8F4, MEBU, FIANAC)
#define IOCTL_READ_TX_SLOT          CTL_CODE(FIDEUN, 0x8F5, MEBU, FIANAC)
#define IOCTL_READ_RX_SLOT          CTL_CODE(FIDEUN, 0x8F6, MEBU, FIANAC)
// \--------------------------

#define IOCTL_MEM_READ				CTL_CODE(FIDEUN, 0x900, MEBU, FIANAC)
#define IOCTL_MEM_WRITE				CTL_CODE(FIDEUN, 0x910, MEBU, FIANAC)
#define IOCTL_MEM_BLOCK_READ		CTL_CODE(FIDEUN, 0x920, MEBU, FIANAC)
#define IOCTL_MEM_BLOCK_WRITE		CTL_CODE(FIDEUN, 0x930, MEBU, FIANAC)
#define IOCTL_SETEVENT				CTL_CODE(FIDEUN, 0x940, MEBU, FIANAC)
#define IOCTL_CHKEVENT				CTL_CODE(FIDEUN, 0x950, MEBU, FIANAC)

#define IOCTL_WRITE_DATA_MASTER		CTL_CODE(FIDEUN, 0x960, MEBU, FIANAC)
#define IOCTL_READ_DATA_MASTER		CTL_CODE(FIDEUN, 0x970, MEBU, FIANAC)

#endif
